add_newline = false

[character]
success_symbol = "[\\$](bold yellow)"
error_symbol = "[\\$](bold yellow)"

[directory]
truncation_length = 100
style = "bold fg:blue"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[username]
style_user = 'bold fg:green'
show_always = true
format = "[$user@]($style)"

[hostname]
ssh_only = false
style = "bold fg:green "
format = "[$hostname]($style) "

[shlvl]
disabled = false
threshold = 1

[status]
disabled = false
format = "[$status ]($style)"

[cmd_duration]
min_time = 0
format = "([$duration]($style))"
show_notifications = true
notification_timeout = 60000

[sudo]
disabled = false

[localip]
disabled = false

[memory_usage]
disabled = false

[time]
disabled = false
style = "green"
format = '[$time]($style) '
time_format = "%R"

